name: copernicus
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - cartopy
  - matplotlib
  - ipywidgets
  - requests
  - rioxarray
  - ipyleaflet
  - holoviews
  - bokeh
  - xarray
  - netCDF4
  - bottleneck
  - urllib3
  - pandas
  - pip
  - pip:
    - pyviz
    - hvplot
