name: copernicus
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - pandas
  - numpy
  - cartopy
  - matplotlib
  - hvplot
  - holoviews
  - bokeh
  - ipywidgets
  - base64
  - json
  - requests
  - rioxarray
  - urllib
  - ipyleaflet