name: copernicus
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - cartopy
  - matplotlib
  - ipywidgets
  - requests
  - rioxarray
  - ipyleaflet
  - xarray
  - netCDF4
  - bottleneck
  - urllib3
  - pandas
  - networkx
  - zipfile
  - imageio
  - pip
